### ISSUE TITLE
all 6 functions need to have access to all community objects as local()

### ISSUE THREAD

**Issue by amyxzhang** [amyxzhang/policykit#64] opened 2020-07-09 19:49 UTC
they already have the action and policy in question

but need access to all other actions, policies, votes, users... in the community

they should be querysets from querying the DB for community-specific objects so that the code can filter on the result using Django ORM

should NOT be able to access objs from other communities.

**Comment by rickygv99** [comment] 2020-07-31 02:34
duplicate of #90

**Closed by rickygv99** 2020-07-31 02:34 UTC
